config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: 'pins#index' 
  	resources :pins
end

app/models/pin.rb
class Pin < ActiveRecord::Base
	validates :title, presence: true
	validates :decription, presence: true
	validates :image, presence: true
	validates :link, presence: true

	mount_uploader :image, PinImageUploader

	belongs_to :user


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :pins
 
  def avatar
  	"http://www.gravatar.com/avatar/#{ Digest::MD5.hexdigest(self.email) }"         	
  end       
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    #@pin = Pin.new(pin_params)
    @pin = current_user.pins.build(pin_params) #pin del user dentro de su lista

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pins_path, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:title, :decription, :image, :link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photos</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render "partials/navigation" %>		
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>	
<%= yield %>

</body>
</html>

app/views/partials/_navigation.html.erb
<header class="color">
  <nav class="navbar navbar-inverse nav-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
          <h3>
            <%= link_to "Photos AE", pins_path%>          
          </h3>                         
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">      
          <ul class="nav navbar-nav navbar-right">     
              <% if current_user %>
                <li>
                    <%= link_to new_pin_path do %>
                      <i class="glyphicon glyphicon-plus "></i>
                    <% end %>
                </li>

                <li class="dropdown">
                  <a data-toggle="dropdown" href="#">
                    <%= image_tag current_user.avatar, width:25, height:25 %>
                    <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
                    <li> <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> </li>
                  </ul>
                </li>
              <% else %>                  
                  <li> <%= link_to 'Sign up', new_user_registration_path %> </li>                         
                  <li> <%= link_to 'Sign in', new_user_session_path %> </li>                
              <% end %>

          </ul>
      </div>
    </div>
  </nav>
</header><!-- /header -->

app/views/partials/_pics.html.erb
<div id="pics">
    <% @pins.each do |pin| %>
      <div class="white-panel">
        <div class="pics-info">

            <h6> <%= pin.title %> </h6>

            <div class="img">
              <%= link_to image_tag(pin.image, class: "img-responsive"), pin%>
            </div>

            <span><%= pin.decription %></span> <br>
            <span><%= pin.link %></span><br>
            <span><%= pin.user.email %></span><br>
            <span> <%= I18n.l pin.created_at, format: :short %> </span><br>
            
            <div class="btns">
              <%= link_to 'Editar', edit_pin_path(pin), class: "btn btn-default btn-sm"  %>
              <%= link_to 'Eliminar', pin, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-sm"  %>  
            </div>            
    
        </div> 
      </div>

    <% end %>
</div>    

app/views/pins/_form.html.erb
<%= form_for(@pin, multipart: true) do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :decription %><br>
    <%= f.text_area :decription %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_field :link %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing Pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<div class="container text-center">
  	<%= render "partials/pics" %> 
</div>

app/views/pins/new.html.erb
<h1>New Pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @pin.title %>
</p>

<p>
  <strong>Decription:</strong>
  <%= @pin.decription %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @pin.image %>
</p>

<p>
  <strong>Link:</strong>
  <%= @pin.link %>
</p>

<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>